name: Build Signed AAB

on:
  push:
    branches:
      - main # 如果你的主分支名叫 master，请改为 master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version: '17'

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.x'
          channel: 'stable'

      - name: Install Dependencies
        run: flutter pub get

      - name: Build AAB
        run: flutter build appbundle --release

      - name: Sign AAB
        uses: r0adkll/sign-android-release@v1
        id: sign_app
        with:
          releaseDirectory: build/app/outputs/bundle/release
          signingKeyBase64: ${{ secrets.KEYSTORE_BASE64 }}
          alias: ${{ secrets.KEY_ALIAS }}
          keyStorePassword: ${{ secrets.KEY_PASSWORD }}
          keyPassword: ${{ secrets.KEY_PASSWORD }}

      - name: Upload Signed AAB
        uses: actions/upload-artifact@v4
        with:
          name: release-signed-aab
          path: ${{steps.sign_app.outputs.signedReleaseFile}}